Release/1.1.0
Komtet/komtetkassa-cs-cart pull request #1
Opened 2018-12-12 14:16 UTC by zeleng

2018-12-14 06:35 UTC, keipaglows commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +     * банковским платежным агентом
банковским платежным агентом банковским платежным агентом

2018-12-14 06:43 UTC, mini4 requested changes

2018-12-14 06:43 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +<?php
Считаю, что исходный код sdk нужно исключить из данного плагина и подключить его, как сторонний пакет

2018-12-14 07:17 UTC, keipaglows commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +     * банковским платежным агентом
банковским платежным агентом банковским платежным агентом

2018-12-14 07:17 UTC, keipaglows commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +     * банковским платежным субагентом
банковским платежным агентом банковским платежным субагентом

2018-12-14 07:17 UTC, keipaglows commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Payment.php
> +     * Электронными
Странно что документация кода где то на английском, а где то на русском

2018-12-14 07:17 UTC, keipaglows commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
>  class komtetHelper
Что бы в итоге этот класс не делал, но komtetHelper - совсем не говорящее название.

2018-12-14 07:59 UTC, zeleng commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +<?php
я не вижу в этом особого удобства. по сути и тот, и тот варианты - это зафиксированная версия сдк, с которой работает плагин. если хранить сдк отдельно, придется добавлять его вручную при каждой сборке плагина.

2018-12-14 08:51 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/kassa/Agent.php
> +<?php
Думаю, что нужно отдельно zip-архив собирать с исходниками sdk. GitHub создает архивы не с целью формирования полноценного плагина для какой то cms, а всего лишь архивирует исходных плагин в текущей версии. GitHub не является marketplace'ом. GitHub - это репозитории исходного кода. А плагин для cs-card и sdk - два разных проекта, один из которых использует другой.

2018-12-14 08:58 UTC, mini4 commented
Обязательное наличие CHANGELOG

2019-01-18 15:05 UTC, zeleng commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
>  class komtetHelper
это основной и единственный кастомный класс в плагине, который выполняет основную функцию, его ни с кем не спутать. поэтому я думаю что его можно было назвать как угодно, хоть my_class. название komtetHelper выбрано для однообразия со всеми остальными плагинами.

2019-01-21 07:42 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +                                        round($position['price'], 2), // price with discount of position
api ожидает цену без скидки, а скидку игнорирует считая самостоятельно

2019-01-21 07:42 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +        $check->applyDiscount($orderDiscount);
Скидка по позициям может быть не равномерно распределена, как делает applyDiscount. Для правильной реализации должен высчитываться тотал позиции в зависимости от скидки.

2019-01-22 07:00 UTC, zeleng commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +        $check->applyDiscount($orderDiscount);
у позиций могут отличаться размеры скидок. на что-то дано 5%, на что-то 10%. изначально позиции записываются с теми скидками, которые даны на них. а потом считается разница между общей ценой чека и суммой позиций со всеми скидками, результатом будет размер скидки по купону (общей на чек). и эта общая скидка затем размазывается равномерно функцией applyDiscount.

2019-01-22 07:00 UTC, zeleng commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +                                        round($position['price'], 2), // price with discount of position
если передавать цены без скидок, то на api не сойдется сумма по оплатам и сумма по позициям.

2019-01-22 07:29 UTC, keipaglows approved these changes

2019-01-22 12:31 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +                                        round($position['price'], 2), // price with discount of position
price не влияет на эту проверку. А вот если цена будет со скидкой, то в чеке не будет скидка отражена.

2019-01-22 12:31 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +                                        round($position['amount']*$position['price'], 2),
дублирования кода для подсчета общей суммы по позиции.

2019-01-22 12:31 UTC, mini4 commented on app/addons/rus_komtet_kassa/Tygh/Addons/RusKomtetKassa/komtethelper.php
> +        $check->applyDiscount($orderDiscount);
ОК. Осознал. Согласен.

2019-01-23 07:04 UTC, mini4 approved these changes

2019-01-23 11:44 UTC, merged